const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"船舶类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryChaunbo"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"维修成本类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryChengben"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"公告类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryGonggao"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"故障类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryGuzhang"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"维保计划类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryWeibaojihua"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"船家管理",
                        "menuJump":"列表",
                        "tableName":"chuanjia"
                    }
                ],
                "menu":"船家管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"船舶管理",
                        "menuJump":"列表",
                        "tableName":"chaunbo"
                    }
                ],
                "menu":"船舶管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"维保公司管理",
                        "menuJump":"列表",
                        "tableName":"weibaogongsi"
                    }
                ],
                "menu":"维保公司管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"维保人员管理",
                        "menuJump":"列表",
                        "tableName":"weibaorenyuan"
                    }
                ],
                "menu":"维保人员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"维保计划管理",
                        "menuJump":"列表",
                        "tableName":"weibaojihua"
                    }
                ],
                "menu":"维保计划管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "报表",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"故障上报管理",
                        "menuJump":"列表",
                        "tableName":"guzhang"
                    }
                ],
                "menu":"故障上报管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"维修成本管理",
                        "menuJump":"列表",
                        "tableName":"chengben"
                    }
                ],
                "menu":"维修成本管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"船舶管理",
                        "menuJump":"列表",
                        "tableName":"chaunbo"
                    }
                ],
                "menu":"船舶管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"维保公司管理",
                        "menuJump":"列表",
                        "tableName":"weibaogongsi"
                    }
                ],
                "menu":"维保公司管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "审核"
                        ],
                        "menu":"维保计划管理",
                        "menuJump":"列表",
                        "tableName":"weibaojihua"
                    }
                ],
                "menu":"维保计划管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"故障上报管理",
                        "menuJump":"列表",
                        "tableName":"guzhang"
                    }
                ],
                "menu":"故障上报管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"船家",
        "tableName":"chuanjia"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"船舶管理",
                        "menuJump":"列表",
                        "tableName":"chaunbo"
                    }
                ],
                "menu":"船舶管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"维保人员管理",
                        "menuJump":"列表",
                        "tableName":"weibaorenyuan"
                    }
                ],
                "menu":"维保人员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除"
                        ],
                        "menu":"维保计划管理",
                        "menuJump":"列表",
                        "tableName":"weibaojihua"
                    }
                ],
                "menu":"维保计划管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"故障上报管理",
                        "menuJump":"列表",
                        "tableName":"guzhang"
                    }
                ],
                "menu":"故障上报管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"维修成本管理",
                        "menuJump":"列表",
                        "tableName":"chengben"
                    }
                ],
                "menu":"维修成本管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"维保公司",
        "tableName":"weibaogongsi"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"船舶管理",
                        "menuJump":"列表",
                        "tableName":"chaunbo"
                    }
                ],
                "menu":"船舶管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"维保计划管理",
                        "menuJump":"列表",
                        "tableName":"weibaojihua"
                    }
                ],
                "menu":"维保计划管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"故障上报管理",
                        "menuJump":"列表",
                        "tableName":"guzhang"
                    }
                ],
                "menu":"故障上报管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"维修成本管理",
                        "menuJump":"列表",
                        "tableName":"chengben"
                    }
                ],
                "menu":"维修成本管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"维保人员",
        "tableName":"weibaorenyuan"
    }
]
    }
}
export default menu;
